### ISSUE TITLE
How can I change the logo of login panel ?

### ISSUE THREAD

**Issue by khalilmebarkia** [thm-projects/arsnova-mobile#62] opened 2016-06-22 09:56 UTC
Hello ARSnova team,
I want to change the logo of login panel, when you login as a teacher you find two button : Guest and ARSnova, I want to change ARSnova to other name, I tried to search into the mobile app but I didn't find the line. 
Thank you

**Comment by Rillke** [comment] 2016-07-02 21:45
In `arsnova.properties`, you have an entry **`security.user-db.title`**, `security.ldap.title` and `security.custom-login.title` which allow you adjusting the text below the Auth-method buttons.

There is also a `security.user-db.image` and for `ldap` and `custom-login` accordingly which I guess is for the image but I haven't looked into that is supposed to work, yet. I just see arsnova.thm.de appears to use a custom font containing their icon.

**Comment by Rillke** [comment] 2016-07-02 21:49
Duplicate of #59 ?

**Closed** 2016-07-07 15:15 UTC
Labels: duplicate

**Comment by deada92** [comment] 2016-10-11 18:35
check out #70

**Comment by deada92** [comment] 2016-10-12 06:15
checkout #70
